### ISSUE TITLE
交易大厅画面K线图不显示

### ISSUE THREAD

**Issue by blueplanet** [blueplanet/peatio#16]
服务器500错误

```ruby
I, [2017-09-10T21:10:25.981056 #64971]  INFO -- : Started GET "/api/v2/k_with_pending_trades.json?market=btccny&limit=768&period=60&trade_id=1" for 106.168.198.110 at 2017-09-10 21:
10:25 +0900
F, [2017-09-10T21:10:25.985306 #64971] FATAL -- :
NoMethodError (undefined method `[]' for nil:NilClass):
  app/api/api_v2/k.rb:28:in `block in <class:K>'
  lib/middleware/security.rb:11:in `call'


```

**Comment by blueplanet** [comment]
执行`bundle exec rake daemons:status`确认K线图的进程是否启动。
如果有启动错误，就没有办法显示数据了。
